const path = require('path')
const { AudioFile } = require('fluid-music').techniques
module.exports = {
  "mono-ride-a.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/mono-ride-a.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":1,"bitrate":88200,"lossless":true,"numberOfSamples":330750,"duration":7.5} }),
  "mono-ride-b.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/mono-ride-b.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":1,"bitrate":88200,"lossless":true,"numberOfSamples":449820,"duration":10.2} }),
  "mono-ride-c.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/mono-ride-c.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":1,"bitrate":88200,"lossless":true,"numberOfSamples":317519,"duration":7.199977324263038} }),
  "mono-ride-d.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/mono-ride-d.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":1,"bitrate":88200,"lossless":true,"numberOfSamples":423360,"duration":9.6} }),
  "stereo-ride-a.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/stereo-ride-a.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":2,"bitrate":352800,"lossless":true,"numberOfSamples":238139,"duration":5.3999773242630384} }),
  "stereo-ride-b.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/stereo-ride-b.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":2,"bitrate":352800,"lossless":true,"numberOfSamples":621811,"duration":14.10002267573696} }),
  "stereo-ride-c.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/stereo-ride-c.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":2,"bitrate":352800,"lossless":true,"numberOfSamples":489509,"duration":11.099977324263039} }),
  "stereo-ride-d.wav": new AudioFile({ path: path.join(__dirname, path.normalize("audio/stereo-ride-d.wav")), info: {"tagTypes":[],"trackInfo":[],"container":"WAVE","codec":"PCM","bitsPerSample":16,"sampleRate":44100,"numberOfChannels":2,"bitrate":352800,"lossless":true,"numberOfSamples":449820,"duration":10.2} }),
};
